#!/usr/bin/env python3
"""Extract every tool's full definition from source, verbatim.

The point is debuggability: a tool's real contract is its name, the text the model
reads to decide whether to call it, the parameter schema the framework validates
against, and the strings it answers with — including the refusals, which is where
most of the harness's behaviour actually lives. None of that is visible in a list of
tool names, and a hand-written summary of it goes stale the first time somebody
tightens a validation.

So this reads the TypeScript and pulls the blocks out unmodified. It is a
source extractor and not a parser: what it prints is what is in the file, which
means it cannot drift from the code and cannot quietly paraphrase a refusal.

Writes markdown to stdout, or to --out.

    smoke/dump-tool-contract.py --out docs/09-agent-contract.md
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: Where tools are defined, and who ends up holding them. The grouping is by
#: module because that is how the code is organised; the per-role allowlist is in
#: `personas.ts` and is printed separately by `dump-agent-contract.ts`.
SOURCES: list[tuple[str, str]] = [
    ("src/runtime/collaborators.ts", "Writer and verifier tools (the scene transaction's own)"),
    ("src/runtime/plan.ts", "Planning tools (orchestrator)"),
    ("src/runtime/orchestration.ts", "Delegation and scene-control tools (orchestrator)"),
    ("src/agents/index-manager-tools.ts", "Index write tools (index-manager only)"),
    ("src/runtime/packet-builder.ts", "Context packet tools (context-builder)"),
    ("src/agents/memory-tools.ts", "Memory tools (every role)"),
    ("src/agents/skill-tools.ts", "Skill tools (every role)"),
    ("src/tools/read-index.ts", "Batched index read (every role but the writer)"),
    ("src/tools/relation-tool.ts", "Relation history (every role)"),
    ("src/tools/pi-tools.ts", "Shell and single-file read, budgeted (every role but the writer)"),
    ("src/tools/shell.ts", "Shell policy: what is refused and why"),
]

TOOL_START = re.compile(r"^(\s*)(?:\{|\.\.\.)?\s*$|^\s*name:\s*\"([a-z_]+)\"", re.M)


def blocks(text: str) -> list[tuple[str, str]]:
    """(name, verbatim block) for each tool literal, found by its `name:` field."""
    out = []
    for m in re.finditer(r"^([ \t]*)name:\s*\"([a-z_]+)\",", text, re.M):
        indent, name = m.group(1), m.group(2)
        # Walk back to the opening brace of the object literal, and forward to the
        # line where the indentation returns to it. Cheap, and correct for this
        # codebase's formatting, which is prettier's.
        start = text.rfind("{", 0, m.start())
        line_start = text.rfind("\n", 0, start) + 1
        depth = 0
        i = start
        while i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        out.append((name, text[line_start : i + 1]))
    return out


def refusals(text: str) -> list[str]:
    """The `rejected:`/`refused:` strings, which are the enforced rules."""
    found = []
    for m in re.finditer(r"`(rejected:|refused:)([^`]{0,400})`", text, re.S):
        found.append((m.group(1) + m.group(2)).replace("\n", " "))
    for m in re.finditer(r"\"(rejected:|refused:)([^\"]{0,300})\"", text, re.S):
        found.append((m.group(1) + m.group(2)).replace("\n", " "))
    return found


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    args = ap.parse_args()

    lines: list[str] = [
        "# Agent contract: every tool, verbatim from source",
        "",
        "Generated by `smoke/dump-tool-contract.py`, which extracts the blocks rather than",
        "describing them, so this page cannot drift from the code. For each tool: the name the",
        "model calls, the `description` it reads when deciding to call it, and the parameter",
        "schema the framework validates against. Refusal strings are listed per module because",
        "they are where most of the harness's enforced behaviour lives — a tool that accepts a",
        "malformed delta is a tool with no contract.",
        "",
        "The per-role allowlist (which of these each worker may call, its model and its",
        "reasoning level) is in `debug/agents.md`; the assembled system prompts are under",
        "`debug/prompts/`.",
        "",
    ]

    total = 0
    for rel, heading in SOURCES:
        path = REPO / rel
        if not path.is_file():
            lines += [f"## {heading}", "", f"`{rel}` — not found", ""]
            continue
        text = path.read_text()
        found = blocks(text)
        total += len(found)
        lines += [f"## {heading}", "", f"Source: `{rel}` — {len(found)} tool(s)", ""]
        for name, block in found:
            lines += [f"### `{name}`", "", "```ts", block.rstrip(), "```", ""]
        rej = refusals(text)
        if rej:
            lines += [f"**Refusals in `{Path(rel).name}` ({len(rej)}):**", ""]
            for r in rej:
                lines += [f"- `{' '.join(r.split())[:300]}`"]
            lines += [""]

    lines += ["---", "", f"{total} tool definition(s) extracted.", ""]
    doc = "\n".join(lines)
    if args.out:
        out = REPO / args.out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(doc)
        print(f"wrote {out} ({len(doc):,} chars, {total} tools)")
    else:
        print(doc)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
