/**
 * Write out what each worker is actually given: its system prompt and its tools.
 *
 * The prompts live in six files and the tools in nine modules, and neither is what a
 * worker receives — the prompt is `SHARED.md` plus the role's own file plus, on a
 * Chinese task, a directive and a different pair of files; the tool list is a
 * persona allowlist intersected with what the factory built. Reading the sources
 * tells you what we meant. This writes what we send.
 *
 *   node --experimental-strip-types smoke/dump-agent-contract.ts debug/
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  DELEGATION_TOOLS,
  MEMORY_TOOLS,
  PERSONAS,
  READ_TOOLS,
  SEARCH_TOOLS,
  personaFor,
  systemPromptFor,
  toolNamesFor,
} from "../src/agents/personas.ts";
import type { AgentRole } from "../src/transaction/types.ts";

const out = path.resolve(process.argv[2] ?? "debug");
const agentsRoot = path.resolve(import.meta.dirname, "../agents");
mkdirSync(path.join(out, "prompts"), { recursive: true });

const lines: string[] = [
  "# What each worker is given",
  "",
  "Generated by `smoke/dump-agent-contract.ts`. Prompt files under `prompts/`.",
  "",
];

for (const persona of PERSONAS) {
  const role = persona.role as AgentRole;
  const en = systemPromptFor(role, agentsRoot);
  const zh = systemPromptFor(role, agentsRoot, { manuscriptLanguage: "chinese" });
  writeFileSync(path.join(out, "prompts", `${role}.en.md`), en);
  writeFileSync(path.join(out, "prompts", `${role}.zh.md`), zh);

  const names = toolNamesFor(role);
  const own = personaFor(role).writeTools;
  lines.push(
    `## ${role}`,
    "",
    `- model: \`${persona.model}\`, thinkingLevel: \`${persona.thinkingLevel ?? "off"}\``,
    `- may delegate: ${persona.mayDelegate}`,
    `- system prompt: ${en.length.toLocaleString()} chars English, ` +
      `${zh.length.toLocaleString()} chars Chinese (${role}.en.md / ${role}.zh.md)`,
    `- tools (${names.length}): ${names.map((n) => `\`${n}\``).join(", ")}`,
    `  - own: ${own.map((n) => `\`${n}\``).join(", ")}`,
    `  - read: ${READ_TOOLS.map((n) => `\`${n}\``).join(", ")}`,
    `  - shell/search: ${
      role === "writer"
        ? "**none — the writer has no shell by design**"
        : SEARCH_TOOLS.map((n) => `\`${n}\``).join(", ")
    }`,
    `  - memory: ${MEMORY_TOOLS.map((n) => `\`${n}\``).join(", ")}`,
    ...(persona.mayDelegate
      ? [`  - delegation: ${DELEGATION_TOOLS.map((n) => `\`${n}\``).join(", ")}`]
      : []),
    "",
  );
}

writeFileSync(path.join(out, "agents.md"), lines.join("\n"));
console.log(`wrote ${out}/agents.md and ${PERSONAS.length * 2} prompt file(s)`);
